/**
 * Design presets inspired by the Personal Finance Desktop Redesign mockups.
 *
 * Each preset defines CSS variable overrides for backgrounds, text, lines,
 * radii, and shadows. The preset also suggests accent colors and fonts,
 * which the user can override through the normal font/color customization.
 *
 * Architecture:
 *   presets.ts  →  theme-context.tsx applies them via inline style
 *                →  ThemeCustomizeModal renders the card selector
 */

export type ThemePresetId =
  | 'default'
  | 'hig'
  | 'material'
  | 'atlas'
  | 'carbon'
  | 'fluent'

export interface ThemePreset {
  id: ThemePresetId
  name: string
  description: string
  vibe: string
  /** Suggested accent (primary) color — user can override in ThemeCustomizeModal. */
  suggestedPrimary: string
  /** Suggested secondary color — user can override. */
  suggestedSecondary: string
  /** Suggested body font — user can override. */
  suggestedBodyFont: string
  /** Suggested brand/heading font — user can override. */
  suggestedBrandFont: string
  /** Suggested mono font — user can override. */
  suggestedMonoFont: string
  /** If true, users can customize colors and fonts freely. Fixed presets disable customization. */
  customizable?: boolean
  /**
   * CSS variable overrides for the light theme.
   * These are applied via document.documentElement.style.setProperty()
   * on top of the base globals.css :root variables.
   */
  light: Record<string, string>
  /**
   * CSS variable overrides for the dark theme.
   * Applied via document.documentElement.style.setProperty()
   * on top of the base [data-theme="dark"] variables.
   * Omitted keys fall through to the base dark theme.
   */
  dark?: Record<string, string>
}

export const PRESETS: ThemePreset[] = [
  /* ── Default: original Notable Finance look ──────────────────────── */
  {
    id: 'default',
    customizable: true,
    name: 'Default',
    description: 'The original Notable Finance look — warm stone, clean sans-serif, balanced spacing.',
    vibe: 'Clean & familiar',
    suggestedPrimary: '#5b6cf9',
    suggestedSecondary: '#0d9488',
    suggestedBodyFont: 'Inter',
    suggestedBrandFont: 'Instrument Serif',
    suggestedMonoFont: 'DM Mono',
    light: {
      '--bg': '#fafaf9',
      '--surface': '#ffffff',
      '--surface-muted': '#f2f1ee',
      '--input-bg': '#f7f6f4',
      '--ink': '#1c1917',
      '--ink-soft': '#44403c',
      '--ink-muted': '#79716b',
      '--line': 'rgba(28,25,23,0.09)',
      '--line-strong': 'rgba(28,25,23,0.14)',
      '--radius': '12px',
      '--btn-radius': '8px',
      '--card-radius': '12px',
      '--shadow': '0 18px 40px rgba(28,25,23,0.08)',
      '--space-1': '2px',
      '--space-2': '4px',
      '--space-3': '8px',
      '--space-4': '12px',
      '--space-5': '16px',
      '--space-6': '20px',
      '--space-7': '24px',
      '--space-8': '32px',
      '--space-9': '40px',
      '--space-10': '48px',
      '--ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
      '--ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
      '--ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      '--duration-fast': '150ms',
      '--duration-normal': '250ms',
      '--duration-slow': '400ms',
    },
    dark: {
      '--bg': '#1c1917',
      '--surface': '#292524',
      '--surface-muted': '#1c1917',
      '--input-bg': '#44403c',
      '--ink': '#fafaf9',
      '--ink-soft': '#d6d3d1',
      '--ink-muted': '#a8a29e',
      '--line': 'rgba(250,250,249,0.09)',
      '--line-strong': 'rgba(250,250,249,0.14)',
      '--radius': '12px',
      '--btn-radius': '8px',
      '--card-radius': '12px',
      '--shadow': '0 18px 40px rgba(0,0,0,0.3)',
    },
  },
  {
    id: 'hig',
    name: 'HIG',
    description: 'Liquid glass Apple design with deep gradients, frosted surfaces, vibrant neons, and polished pill buttons.',
    vibe: 'Liquid glass',
    suggestedPrimary: '#007AFF',
    suggestedSecondary: '#30D158',
    suggestedBodyFont: 'system-ui',
    suggestedBrandFont: 'system-ui',
    suggestedMonoFont: 'Courier New',
    light: {
      '--bg': '#f0f1f5',
      '--surface': '#ffffff',
      '--surface-muted': '#e8e9ef',
      '--input-bg': '#fafafa',
      '--ink': 'rgba(0,0,0,0.92)',
      '--ink-soft': 'rgba(0,0,0,0.60)',
      '--ink-muted': 'rgba(0,0,0,0.40)',
      '--line': 'rgba(60,60,67,0.10)',
      '--line-strong': 'rgba(60,60,67,0.20)',
      '--radius': '16px',
      '--btn-radius': '999px',
      '--card-radius': '18px',
      '--shadow': '0 12px 40px rgba(0,0,0,0.10), 0 4px 12px rgba(0,0,0,0.06), 0 1px 3px rgba(0,0,0,0.04)',
      '--space-1': '2px',
      '--space-2': '4px',
      '--space-3': '8px',
      '--space-4': '12px',
      '--space-5': '16px',
      '--space-6': '20px',
      '--space-7': '24px',
      '--space-8': '32px',
      '--space-9': '40px',
      '--space-10': '48px',
      '--ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
      '--ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
      '--ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      '--duration-fast': '150ms',
      '--duration-normal': '250ms',
      '--duration-slow': '400ms',
    },
    dark: {
      '--bg': '#0d0d14',
      '--surface': '#1c1c26',
      '--surface-muted': '#2a2a36',
      '--input-bg': '#23232f',
      '--ink': 'rgba(255,255,255,0.92)',
      '--ink-soft': 'rgba(255,255,255,0.62)',
      '--ink-muted': 'rgba(255,255,255,0.40)',
      '--line': 'rgba(120,120,130,0.20)',
      '--line-strong': 'rgba(120,120,130,0.35)',
      '--radius': '16px',
      '--btn-radius': '999px',
      '--card-radius': '18px',
      '--shadow': '0 12px 40px rgba(0,0,0,0.45), 0 4px 12px rgba(0,0,0,0.25), 0 1px 3px rgba(0,0,0,0.12)',
      '--space-1': '2px',
      '--space-2': '4px',
      '--space-3': '8px',
      '--space-4': '12px',
      '--space-5': '16px',
      '--space-6': '20px',
      '--space-7': '24px',
      '--space-8': '32px',
      '--space-9': '40px',
      '--space-10': '48px',
      '--ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
      '--ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
      '--ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      '--duration-fast': '150ms',
      '--duration-normal': '250ms',
      '--duration-slow': '400ms',
    },
  },
  {
    id: 'material',
    name: 'Material',
    description: 'Material Design 3 with tonal palette, rounded corners, and dynamic elevation.',
    vibe: 'Material You',
    suggestedPrimary: '#6750A4',
    suggestedSecondary: '#625B71',
    suggestedBodyFont: 'Roboto',
    suggestedBrandFont: 'Roboto',
    suggestedMonoFont: 'Fira Code',
    light: {
      '--bg': '#FFFBFE',
      '--surface': '#F6EDFF',
      '--surface-muted': '#E8DEF8',
      '--input-bg': '#F3EDF7',
      '--ink': '#1C1B1F',
      '--ink-soft': '#49454F',
      '--ink-muted': '#79747E',
      '--line': 'rgba(28,27,31,0.08)',
      '--line-strong': 'rgba(28,27,31,0.14)',
      '--radius': '12px',
      '--btn-radius': '20px',
      '--card-radius': '16px',
      '--shadow': '0 1px 3px rgba(0,0,0,0.15), 0 4px 8px rgba(0,0,0,0.08)',
      '--space-1': '2px',
      '--space-2': '4px',
      '--space-3': '8px',
      '--space-4': '12px',
      '--space-5': '16px',
      '--space-6': '20px',
      '--space-7': '24px',
      '--space-8': '32px',
      '--space-9': '40px',
      '--space-10': '48px',
      '--ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
      '--ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
      '--ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      '--duration-fast': '150ms',
      '--duration-normal': '250ms',
      '--duration-slow': '400ms',
    },
    dark: {
      '--bg': '#1C1B1F',
      '--surface': '#2B2930',
      '--surface-muted': '#332F3A',
      '--input-bg': '#332F3A',
      '--ink': '#E6E1E5',
      '--ink-soft': '#CAC4D0',
      '--ink-muted': '#938F99',
      '--line': 'rgba(230,225,229,0.08)',
      '--line-strong': 'rgba(230,225,229,0.14)',
      '--radius': '12px',
      '--btn-radius': '20px',
      '--card-radius': '16px',
      '--shadow': '0 2px 6px rgba(0,0,0,0.35), 0 6px 16px rgba(0,0,0,0.25)',
      '--space-1': '2px',
      '--space-2': '4px',
      '--space-3': '8px',
      '--space-4': '12px',
      '--space-5': '16px',
      '--space-6': '20px',
      '--space-7': '24px',
      '--space-8': '32px',
      '--space-9': '40px',
      '--space-10': '48px',
      '--ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
      '--ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
      '--ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      '--duration-fast': '150ms',
      '--duration-normal': '250ms',
      '--duration-slow': '400ms',
    },
  },
  {
    id: 'atlas',
    name: 'Atlas',
    description: 'Atlassian Design System with clean blue primary, structured dividers, and precise spacing.',
    vibe: 'Enterprise structured',
    suggestedPrimary: '#0052CC',
    suggestedSecondary: '#36B37E',
    suggestedBodyFont: 'Work Sans',
    suggestedBrandFont: 'Work Sans',
    suggestedMonoFont: 'JetBrains Mono',
    light: {
      '--bg': '#F4F5F7',
      '--surface': '#FFFFFF',
      '--surface-muted': '#EBECF0',
      '--input-bg': '#FAFBFC',
      '--ink': '#172B4D',
      '--ink-soft': '#42526E',
      '--ink-muted': '#7A869A',
      '--line': 'rgba(23,43,77,0.08)',
      '--line-strong': 'rgba(23,43,77,0.16)',
      '--radius': '3px',
      '--btn-radius': '3px',
      '--card-radius': '3px',
      '--shadow': '0 1px 1px rgba(9,30,66,0.08), 0 2px 4px rgba(9,30,66,0.06)',
      '--space-1': '2px',
      '--space-2': '4px',
      '--space-3': '8px',
      '--space-4': '12px',
      '--space-5': '16px',
      '--space-6': '20px',
      '--space-7': '24px',
      '--space-8': '32px',
      '--space-9': '40px',
      '--space-10': '48px',
      '--ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
      '--ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
      '--ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      '--duration-fast': '150ms',
      '--duration-normal': '250ms',
      '--duration-slow': '400ms',
    },
    dark: {
      '--bg': '#0D1114',
      '--surface': '#161A1D',
      '--surface-muted': '#1E2328',
      '--input-bg': '#1E2328',
      '--ink': '#E6EDF5',
      '--ink-soft': '#B8C7D9',
      '--ink-muted': '#8C9CB0',
      '--line': 'rgba(230,237,245,0.08)',
      '--line-strong': 'rgba(230,237,245,0.16)',
      '--radius': '3px',
      '--btn-radius': '3px',
      '--card-radius': '3px',
      '--shadow': '0 1px 2px rgba(0,0,0,0.25), 0 3px 8px rgba(0,0,0,0.2)',
      '--space-1': '2px',
      '--space-2': '4px',
      '--space-3': '8px',
      '--space-4': '12px',
      '--space-5': '16px',
      '--space-6': '20px',
      '--space-7': '24px',
      '--space-8': '32px',
      '--space-9': '40px',
      '--space-10': '48px',
      '--ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
      '--ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
      '--ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      '--duration-fast': '150ms',
      '--duration-normal': '250ms',
      '--duration-slow': '400ms',
    },
  },
  {
    id: 'carbon',
    name: 'Carbon',
    description: 'IBM Carbon Design System with Plex font, blue primary, structured hierarchy.',
    vibe: 'Enterprise precise',
    suggestedPrimary: '#0F62FE',
    suggestedSecondary: '#24A148',
    suggestedBodyFont: 'IBM Plex Sans',
    suggestedBrandFont: 'IBM Plex Sans',
    suggestedMonoFont: 'IBM Plex Mono',
    light: {
      '--bg': '#F4F4F4',
      '--surface': '#FFFFFF',
      '--surface-muted': '#E0E0E0',
      '--input-bg': '#F4F4F4',
      '--ink': '#161616',
      '--ink-soft': '#525252',
      '--ink-muted': '#8D8D8D',
      '--line': 'rgba(22,22,22,0.12)',
      '--line-strong': 'rgba(22,22,22,0.25)',
      '--radius': '0px',
      '--btn-radius': '0px',
      '--card-radius': '0px',
      '--shadow': '0 1px 2px rgba(0,0,0,0.1)',
      '--space-1': '2px',
      '--space-2': '4px',
      '--space-3': '8px',
      '--space-4': '12px',
      '--space-5': '16px',
      '--space-6': '20px',
      '--space-7': '24px',
      '--space-8': '32px',
      '--space-9': '40px',
      '--space-10': '48px',
      '--ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
      '--ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
      '--ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      '--duration-fast': '150ms',
      '--duration-normal': '250ms',
      '--duration-slow': '400ms',
    },
    dark: {
      '--bg': '#262626',
      '--surface': '#393939',
      '--surface-muted': '#525252',
      '--input-bg': '#393939',
      '--ink': '#F4F4F4',
      '--ink-soft': '#C6C6C6',
      '--ink-muted': '#8D8D8D',
      '--line': 'rgba(244,244,244,0.12)',
      '--line-strong': 'rgba(244,244,244,0.25)',
      '--radius': '0px',
      '--btn-radius': '0px',
      '--card-radius': '0px',
      '--shadow': '0 2px 6px rgba(0,0,0,0.3)',
      '--space-1': '2px',
      '--space-2': '4px',
      '--space-3': '8px',
      '--space-4': '12px',
      '--space-5': '16px',
      '--space-6': '20px',
      '--space-7': '24px',
      '--space-8': '32px',
      '--space-9': '40px',
      '--space-10': '48px',
      '--ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
      '--ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
      '--ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      '--duration-fast': '150ms',
      '--duration-normal': '250ms',
      '--duration-slow': '400ms',
    },
  },
  {
    id: 'fluent',
    name: 'Fluent',
    description: 'Microsoft Fluent 2 Design System with effective accents, rounded corners, and soft elevation.',
    vibe: 'Modern Windows',
    suggestedPrimary: '#0078D4',
    suggestedSecondary: '#498205',
    suggestedBodyFont: 'Open Sans',
    suggestedBrandFont: 'Open Sans',
    suggestedMonoFont: 'Inconsolata',
    light: {
      '--bg': '#F3F3F3',
      '--surface': '#FFFFFF',
      '--surface-muted': '#E5E5E5',
      '--input-bg': '#FFFFFF',
      '--ink': '#1A1A1A',
      '--ink-soft': '#484848',
      '--ink-muted': '#6E6E6E',
      '--line': 'rgba(26,26,26,0.06)',
      '--line-strong': 'rgba(26,26,26,0.14)',
      '--radius': '6px',
      '--btn-radius': '4px',
      '--card-radius': '8px',
      '--shadow': '0 1.2px 3.6px rgba(0,0,0,0.1), 0 6.4px 14.4px rgba(0,0,0,0.08)',
      '--space-1': '2px',
      '--space-2': '4px',
      '--space-3': '8px',
      '--space-4': '12px',
      '--space-5': '16px',
      '--space-6': '20px',
      '--space-7': '24px',
      '--space-8': '32px',
      '--space-9': '40px',
      '--space-10': '48px',
      '--ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
      '--ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
      '--ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      '--duration-fast': '150ms',
      '--duration-normal': '250ms',
      '--duration-slow': '400ms',
    },
    dark: {
      '--bg': '#1A1A1A',
      '--surface': '#2D2D2D',
      '--surface-muted': '#383838',
      '--input-bg': '#383838',
      '--ink': '#F5F5F5',
      '--ink-soft': '#BEBEBE',
      '--ink-muted': '#8A8A8A',
      '--line': 'rgba(245,245,245,0.06)',
      '--line-strong': 'rgba(245,245,245,0.14)',
      '--radius': '6px',
      '--btn-radius': '4px',
      '--card-radius': '8px',
      '--shadow': '0 1.2px 3.6px rgba(0,0,0,0.25), 0 6.4px 14.4px rgba(0,0,0,0.2)',
      '--space-1': '2px',
      '--space-2': '4px',
      '--space-3': '8px',
      '--space-4': '12px',
      '--space-5': '16px',
      '--space-6': '20px',
      '--space-7': '24px',
      '--space-8': '32px',
      '--space-9': '40px',
      '--space-10': '48px',
      '--ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
      '--ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
      '--ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      '--duration-fast': '150ms',
      '--duration-normal': '250ms',
      '--duration-slow': '400ms',
    },
  },
]

/** Look up a preset by ID; returns the 'default' preset if not found. */
export function getPreset(id: ThemePresetId): ThemePreset {
  return PRESETS.find((p) => p.id === id) ?? PRESETS[0]
}
