/**
 * The single source of truth for every request/response IPC channel string
 * (refactor_development_plan.md Phase 7.2, fixes F8). `main/ipc/*` registers handlers on
 * these; `preload/index.ts` invokes them. Renaming a channel here is a compile error at
 * every call site instead of a silent runtime "no handler registered for X".
 *
 * Event channels (main → renderer broadcasts, e.g. `records:changed`) are a separate,
 * much smaller set already typed via `EventChannel` in finance.types.ts — out of scope here.
 */
export const IPC_CHANNELS = {
  accountsList: 'accounts:list',
  appPing: 'app:ping',
  backupExport: 'backup:export',
  backupImport: 'backup:import',
  backupInspect: 'backup:inspect',
  categoriesExpense: 'categories:expense',
  categoriesIncome: 'categories:income',
  chatCancelDraft: 'chat:cancelDraft',
  chatConfirmDraft: 'chat:confirmDraft',
  chatCreateCredential: 'chat:createCredential',
  chatCreateThread: 'chat:createThread',
  chatDeleteAllThreads: 'chat:deleteAllThreads',
  chatDeleteCredential: 'chat:deleteCredential',
  chatDeleteThread: 'chat:deleteThread',
  chatDetectProvider: 'chat:detectProvider',
  chatGetThread: 'chat:getThread',
  chatIsAppleOs: 'chat:isAppleOs',
  chatListCredentials: 'chat:listCredentials',
  chatListDrafts: 'chat:listDrafts',
  chatListMessages: 'chat:listMessages',
  chatListThreads: 'chat:listThreads',
  chatModels: 'chat:models',
  chatOverlays: 'chat:overlays',
  chatProviders: 'chat:providers',
  chatRemoteModels: 'chat:remoteModels',
  chatSend: 'chat:send',
  chatSetDefaultCredential: 'chat:setDefaultCredential',
  chatStatus: 'chat:status',
  chatUpdateCredential: 'chat:updateCredential',
  chatUpdateDraft: 'chat:updateDraft',
  chatUpdateThread: 'chat:updateThread',
  dbHealth: 'db:health',
  devLogsAppend: 'devLogs:append',
  devLogsClear: 'devLogs:clear',
  devLogsList: 'devLogs:list',
  expensesCreate: 'expenses:create',
  expensesHardDelete: 'expenses:hardDelete',
  expensesList: 'expenses:list',
  expensesListForCCCoverage: 'expenses:listForCCCoverage',
  expensesSoftDelete: 'expenses:softDelete',
  expensesUpdate: 'expenses:update',
  historyDiscardUnsynced: 'history:discardUnsynced',
  historyGet: 'history:get',
  historyGetItemDetail: 'history:getItemDetail',
  incomesCreate: 'incomes:create',
  incomesGet: 'incomes:get',
  incomesHardDelete: 'incomes:hardDelete',
  incomesList: 'incomes:list',
  incomesSoftDelete: 'incomes:softDelete',
  incomesUpdate: 'incomes:update',
  notionConnect: 'notion:connect',
  notionDisconnect: 'notion:disconnect',
  notionDiscoverDatabases: 'notion:discoverDatabases',
  notionGetMapping: 'notion:getMapping',
  notionIsConnected: 'notion:isConnected',
  notionSaveMapping: 'notion:saveMapping',
  notionVerifySchema: 'notion:verifySchema',
  pageContentClear: 'pageContent:clear',
  pageContentGet: 'pageContent:get',
  pageContentSave: 'pageContent:save',
  reportsDashboard: 'reports:dashboard',
  reportsMonitoringSplit: 'reports:monitoringSplit',
  reportsMonthlyMonitoring: 'reports:monthlyMonitoring',
  schedulerCreate: 'scheduler:create',
  schedulerGenerate: 'scheduler:generate',
  schedulerHardDelete: 'scheduler:hardDelete',
  schedulerList: 'scheduler:list',
  schedulerSoftDelete: 'scheduler:softDelete',
  schedulerUpdate: 'scheduler:update',
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  syncGetSettings: 'sync:getSettings',
  syncInitialPull: 'sync:initialPull',
  syncListConflicts: 'sync:listConflicts',
  syncNow: 'sync:now',
  syncPull: 'sync:pull',
  syncPush: 'sync:push',
  syncReset: 'sync:reset',
  syncResolveAllConflicts: 'sync:resolveAllConflicts',
  syncResolveConflict: 'sync:resolveConflict',
  syncSetMode: 'sync:setMode',
  syncStatus: 'sync:status',
  updaterCheck: 'updater:check',
  updaterInstall: 'updater:install',
  updaterStatus: 'updater:status',
  windowsNew: 'windows:new',
} as const

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]
